version: '3.8'

services:
  nginx:
    depends_on:
      - my-app
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '5050:80'
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  my-app:
    # stdin_open: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: ./Dockerfile
      context: ./my-app
    # volumes:
    #   - ./my-app:/app
    command: npm run dev
    restart: always
    ports:
      - '3000:3000'
